image: alpine:latest

stages:
  - publish

pages:
  stage: publish
  script:
    - mkdir -p ./public
    - cp -r src/* ./public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
