# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag
image: wagnerstephan/bitbucket-git-ftp

pipelines:
  branches:
    prod:
      - step:
          script:
            - git config git-ftp.url "$FTP_URL"
            - git config git-ftp.user "$FTP_LOGIN"
            - git config git-ftp.password "$FTP_PASSWORD"
            - git config git-ftp.syncroot src/
            - git ftp push