# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

pipelines:
  branches:
    prod:
      - step:
          script:
            - echo "Start deploying"
            - apt-get update
            - apt-get -qq install git-ftp
            - echo "'_$(git status -uno --porcelain | wc -l)_'"
            - git status -uno --porcelain
            - echo "Initiating push site:src"
            - git config git-ftp.syncroot src/
            - git ftp init --user $FTP_LOGIN --passwd $FTP_PASSWORD $FTP_URL
            - echo "Deployment complete"